name: Send Telegram Message

on:
  # این خط باعث می‌شود ورک‌فلو با دستور خارجی اجرا شود
  repository_dispatch:
    types: [trigger-event]
  # این خط اجازه می‌دهد هنوز هم دستی تست کنی
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install python-telegram-bot

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
